# Generated by Django 3.2.5 on 2021-07-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsstory_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='story_image',
            field=models.URLField(default='https://www.gaiaresources.com.au/wp-content/uploads/2020/02/SheCodes-cupcakes-narrow.jpg'),
        ),
    ]
