# Generated by Django 3.2.5 on 2021-08-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsstory_story_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsstory',
            name='story_image',
        ),
        migrations.AddField(
            model_name='newsstory',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
